import { randomUUID } from "crypto";
import { count, eq } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { db as appDb } from "../db.js";
import * as pgSchema from "../../shared/schema.pg.js";
import { encryptCredentialSync } from "../credential-crypto.js";
import type {
  ApiKeyPublic,
  Game,
  Indexer,
  InsertPlatformMapping,
  InsertUser,
  User,
} from "../../shared/schema.js";
import type { SyncIndexersResult } from "./transactional-ops.js";

/**
 * Postgres implementations.
 *
 * node-postgres transactions are async: the callback returns a promise and
 * statements are awaited rather than finished with .all()/.run(). Behaviour is
 * intended to match ./transactional-ops.sqlite.ts exactly; only the execution
 * model differs. See ./transactional-ops.ts for why they cannot be one body.
 *
 * This module is only ever loaded with Postgres active, so it can use the
 * Postgres tables and their real types directly instead of the app-wide
 * SQLite-shaped view of the schema.
 */
const { apiKeys, games, indexers, platformMappings, users } = pgSchema;
const db = appDb as unknown as NodePgDatabase<typeof pgSchema>;

export async function seedPlatformMappingsIfEmpty(
  mappings: InsertPlatformMapping[]
): Promise<{ seeded: boolean; count: number }> {
  return db.transaction(async (tx) => {
    const [existing] = await tx.select({ count: count() }).from(platformMappings);
    if (existing.count > 0) {
      return { seeded: false, count: existing.count };
    }

    for (const mapping of mappings) {
      await tx.insert(platformMappings).values({ ...mapping, id: randomUUID() });
    }

    const [seeded] = await tx.select({ count: count() }).from(platformMappings);
    return { seeded: true, count: seeded.count };
  });
}

export async function registerSetupUser(insertUser: InsertUser): Promise<User> {
  return db.transaction(async (tx) => {
    const [result] = await tx.select({ count: count() }).from(users);

    if (result.count > 0) {
      throw new Error("Setup already completed");
    }

    // Ids are generated by the application on both dialects.
    const id = randomUUID();
    const [user] = await tx
      .insert(users)
      .values({ ...insertUser, id, steamId64: null })
      .returning();
    return user;
  });
}

export async function updateGamesBatch(
  updates: { id: string; data: Partial<Game> }[]
): Promise<void> {
  await db.transaction(async (tx) => {
    for (const update of updates) {
      await tx.update(games).set(update.data).where(eq(games.id, update.id));
    }
  });
}

export async function syncIndexers(
  indexersToSync: Partial<Indexer>[],
  encryptionKey: Buffer
): Promise<SyncIndexersResult> {
  const results: SyncIndexersResult = {
    added: 0,
    updated: 0,
    failed: 0,
    errors: [],
  };

  await db.transaction(async (tx) => {
    // Fetch all existing indexers within the transaction to compare against
    const existingIndexers = await tx.select().from(indexers);
    const existingMap = new Map(existingIndexers.map((i) => [i.url, i]));

    for (const idx of indexersToSync) {
      try {
        if (!idx.name || !idx.url || !idx.apiKey) {
          results.failed++;
          results.errors.push(`Skipping ${idx.name || "unknown"} - missing required fields`);
          continue;
        }

        const existing = existingMap.get(idx.url);
        const encryptedApiKey = encryptCredentialSync(idx.apiKey, encryptionKey);

        if (existing) {
          // Explicitly set allowed fields for update to prevent mass assignment
          await tx
            .update(indexers)
            .set({
              name: idx.name,
              url: idx.url,
              apiKey: encryptedApiKey,
              protocol: idx.protocol,
              enabled: idx.enabled,
              priority: idx.priority,
              categories: idx.categories,
              rssEnabled: idx.rssEnabled,
              autoSearchEnabled: idx.autoSearchEnabled,
              updatedAt: new Date(),
            })
            .where(eq(indexers.id, existing.id));
          results.updated++;
        } else {
          const id = randomUUID();
          // Default values for missing optional fields
          const newIndexer = {
            id,
            name: idx.name,
            url: idx.url,
            apiKey: encryptedApiKey,
            protocol: idx.protocol ?? "torznab",
            enabled: idx.enabled ?? true,
            priority: idx.priority ?? 1,
            categories: idx.categories ?? [],
            rssEnabled: idx.rssEnabled ?? true,
            autoSearchEnabled: idx.autoSearchEnabled ?? true,
            createdAt: new Date(),
            updatedAt: new Date(),
          };

          await tx.insert(indexers).values(newIndexer);
          results.added++;
        }
      } catch (error) {
        results.failed++;
        results.errors.push(
          `Failed to sync ${idx.name}: ${error instanceof Error ? error.message : "Unknown error"}`
        );
      }
    }
  });

  return results;
}

export async function addApiKey(
  key: { userId: string; name: string; keyHash: string; prefix: string },
  maxKeys: number
): Promise<ApiKeyPublic> {
  // Counting and inserting inside one transaction closes the race two
  // concurrent requests would otherwise have around the cap: without it,
  // both could read the same under-limit count before either insert lands.
  return db.transaction(async (tx) => {
    const [{ count: existingKeys }] = await tx
      .select({ count: count() })
      .from(apiKeys)
      .where(eq(apiKeys.userId, key.userId));

    if (existingKeys >= maxKeys) {
      throw new Error("API key limit reached");
    }

    const [created] = await tx
      .insert(apiKeys)
      .values({ ...key, id: randomUUID() })
      .returning({
        id: apiKeys.id,
        userId: apiKeys.userId,
        name: apiKeys.name,
        prefix: apiKeys.prefix,
        createdAt: apiKeys.createdAt,
        lastUsedAt: apiKeys.lastUsedAt,
      });
    return created;
  });
}
